<table cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff">
    <tr>
        <td class="middle" style="padding: 5px 10px; white-space: nowrap;">
          Новосибирск<br/>
          ул. Тюменская, 2, корпус 5<br/>
          8 (383) 399-02-10, 325-33-66<br/><br/>
          <a href="mailto:lakost@ngs.ru" class="light">lakost@ngs.ru</a>
          <div style="width:0px; height:5px;"><span></span></div>
          <!--a href="images/map.gif" target="_blank"><img src="images/map.gif" border="0" alt="" width="50"/>Карта-схема</a-->

<a href='http://maps.yandex.ru/?text=%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%2C%20%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D0%B8%D0%B1%D0%B8%D1%80%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C%2C%20%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D0%B8%D0%B1%D0%B8%D1%80%D1%81%D0%BA%2C%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20%D0%A2%D1%8E%D0%BC%D0%B5%D0%BD%D1%81%D0%BA%D0%B0%D1%8F%2C%202&sll=82.946921%2C54.959837&sspn=0.00821%2C0.004725&ll=82.946921%2C54.959837&spn=0.021007%2C0.00' target='_blank' alt='Ссылка на Яндекс.Карты'>Тюменская, 2 — Яндекс.Карты</a>

        </td>
    </tr>
</table>