<a href="http://www.kariguz.ru"><img src="i/partners/cariguz.gif" border="0" alt="" style="margin-right: 20px;"/></a>
<img src="i/partners/atra.gif" border="0" alt="" style="margin-right: 20px;"/>
<a href="http://www.dmtextile.ru"><img src="i/partners/lm.gif" border="0" alt="" style="margin-right: 20px;"/></a>
<a href="http://www.sortex-y.ru"><img src="i/partners/sortex.gif" border="0" alt="" style="margin-right: 20px;"/></a>
<a href="http://evateks.ru"><img src="i/partners/eva.gif" border="0" alt="" style="margin-right: 20px;"/></a>
<!--a href="http://www.kariguz.ru"><img src="i/partners/cariguz2.gif" border="0" alt="" style="margin-right: 20px;"/></a>
<img src="i/partners/paters.gif" border="0" alt="" style="margin-right: 20px;"/>
<img src="i/partners/ozelitek.gif" border="0" alt="" style="margin-right: 20px;"/-->
<a href="http://www.ecotexe.ru"><img src="i/partners/ekotex.gif" border="0" alt="" style="margin-right: 20px;"/></a>
<a href="http://www.melnikov-tex.ru"><img src="i/partners/exo.gif" border="0" alt="" style="margin-right: 20px;"/></a>
<a href="http://www.cotraj.ru"><img src="i/partners/rai.gif" border="0" alt="" style="margin-right: 20px;"/></a>